---
- hosts: baseimage-vm
  become: yes
  tasks:

    - name: install packages
      yum:
        name: selinux-policy-mls
        state: latest

    - name: Enable selinux
      ansible.posix.selinux:
        policy: mls
        state: permissive

    - name: Add user1
      ansible.builtin.user:
        name: user1

    - name: Add user2
      ansible.builtin.user:
        name: user2

    - name: make selinux user
      community.general.selogin:
        login: ictsc
        seuser: sysadm_u

    - name: make selinux user
      community.general.selogin:
        login: user1
        seuser: staff_u
        selevel: s2:c100

    - name: make selinux user
      community.general.selogin:
        login: user2
        seuser: staff_u
        selevel: s1:c200
