---
- hosts: baseimage-vm
  become: yes
  vars:
    - user_password: "WelComeToICTSC2020"
  tasks:

    - name: Permissive selinux
      ansible.posix.selinux:
        policy: mls
        state: permissive

    - name: install packages
      yum:
        name: selinux-policy-mls
        state: latest

    - name: sshd password login
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: "^PasswordAuthentication"
        line: "PasswordAuthentication yes"

    - name: reload sshd
      systemd:
        name: sshd
        state: reloaded

    - name: Add emplyerr group
      ansible.builtin.group:
        name: employees
        state: present

    - name: Add root
      ansible.builtin.user:
        name: root
        password: "{{ user_password | password_hash('sha512') }}"

    - name: Add user
      ansible.builtin.user:
        name: user
        password: "{{ user_password | password_hash('sha512') }}"

        #- name: Allow home directory context
        #  community.general.sefcontext:
        #      target: '/home(/.*)?'
        #      setype: user_home_t
        #      state: present

    - name: relabel home directory
      shell: restorecon -rv /home

    - name: Add employee1
      ansible.builtin.user:
        name: employee1
        group: employees
        password: "{{ user_password | password_hash('sha512') }}"

    - name: Add employee2
      ansible.builtin.user:
        name: employee2
        group: employees
        password: "{{ user_password | password_hash('sha512') }}"

    - name: make user member user top level clearance
      community.general.selogin:
        login: user
        seuser: staff_u
        selevel: s10:c100,c200

    - name: make ictsc member user top level clearance
      community.general.selogin:
        login: ictsc
        seuser: staff_u
        selevel: s10:c100,c200

    - name: make selinux user
      community.general.selogin:
        login: employee1
        seuser: staff_u
        selevel: s1:c100

    - name: make selinux user
      community.general.selogin:
        login: employee2
        seuser: staff_u
        selevel: s2:c200

    - name: directory
      file:
        path: /srv/department
        state: directory
        owner: root
        group: root
        mode: "777"

    - name: directory
      file:
        path: /srv/department/A
        state: directory

    - name: directory
      file:
        path: /srv/department/B
        state: directory

    - name: make file1
      copy:
        content: "This is a sample line."
        dest: /srv/department/A/file1.txt
        selevel: s1:c100

    - name: make file2
      copy:
        content: "This is a sample line."
        dest: /srv/department/B/file2.txt
        selevel: s2:c200

    - name: make file3
      copy:
        content: "This is a sample line."
        dest: /srv/department/B/file3.txt
        selevel: s1:c200

    - name: Enforce selinux
      ansible.posix.selinux:
        state: enforcing
        policy: mls
